version: "3.8"

services:
  penta-mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "7018:27017"
    volumes:
      - penta-data:/data/db
  
  pentamarket-app:
    depends_on:
      - penta-mongo
    build: .
    image: pentamarket
    restart: unless-stopped
    ports:
      - "5001:3001"
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URI=mongodb://penta-mongo:27017/penta-db

volumes:
  penta-data:
